version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes: 
      - ./code:/code
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
    depends_on: 
      - php
    networks: 
      - pndocker
      
  php:
    build: ./build/php
    volumes: 
      - ./code:/code
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./log/php:/var/log/php-fpm.log
    networks: 
      - pndocker

networks: 
  pndocker:
    external: true
